version: "3.7"

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    hostname: mysql
    networks:
      - store-bpel
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 20s
      timeout: 5s
      retries: 5

  admin-bff:
    image: public.ecr.aws/h3x4i1u8/admin-bff:20230428055958
    container_name: admin-bff
    hostname: admin-bff
    networks:
      - store-bpel
    ports:
      - "10000:10000"

  customer-bff:
    image: public.ecr.aws/h3x4i1u8/customer-bff:20230428060052
    container_name: customer-bff
    hostname: customer-bff
    networks:
      - store-bpel
    ports:
      - "20000:20000"

  shared-bff:
    image: public.ecr.aws/h3x4i1u8/shared-bff:20230428060137
    container_name: shared-bff
    hostname: shared-bff
    networks:
      - store-bpel
    ports:
      - "30000:30000"

  event-service-db-migration:
    image: public.ecr.aws/h3x4i1u8/event-service-db-migration:20230429174130
    container_name: event-service-db-migration
    hostname: event-service-db-migration
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - store-bpel

  event-service:
    image: public.ecr.aws/h3x4i1u8/event-service:20230428021514
    container_name: event-service
    hostname: event-service
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - store-bpel
#    configs:
#      - source: event-service-config
#        target: /app/event-service/config.yaml
    ports:
      - "14060:14060"

networks:
  store-bpel:
    name: store-bpel
    driver: bridge

#configs:
#  event-service-config:
#    file: ./event_service/config.yaml
