-- INSERT INTO `customer` (`username`, `customer_name`, `customer_email`, `customer_phone`, `customer_age`, `customer_gender`, `street`, `ward`, `district`, `province`) VALUES
-- ('user1', 'Tran Van Mot', 'user1@gmail.com', '0123456789', 25, 'MALE', 'Ly Thuong Kiet Street', 'Ward 14', 'Dist. 10', 'Ho Chi Minh City'),
-- ('user2', 'Tran Van Hai', 'user2@gmail.com', '0123456782', 25, 'MALE', 'Ly Thuong Kiet Street', 'Ward 14', 'Dist. 10', 'Ho Chi Minh City');
