name: Build Docker images

on:
  push:
    branches: [ "master", "tho/*"]

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: huuthotn01
          password: huutho-trannguyen-235532

      -
        name: Build Docker images
        run: imageTag=`$shell date '+%Y%m%d%H%M%S'` && 
          docker build -f .store-bpel/bff/admin_bff/Dockerfile -t huuthotn01/admin-bff:$imageTag . &&
          docker build -f .store-bpel/bff/customer_bff/Dockerfile -t huuthotn01/customer-bff:$imageTag . &&
          docker build -f .store-bpel/bff/shared_bff/Dockerfile -t huuthotn01/shared-bff:$imageTag . &&
          docker build -f .store-bpel/account_service/Dockerfile -t huuthotn01/account-service:$imageTag . &&
          docker build -f .store-bpel/branch_service/Dockerfile -t huuthotn01/branch-service:$imageTag . &&
          docker build -f .store-bpel/cart_service/Dockerfile -t huuthotn01/cart-service:$imageTag . &&
          docker build -f .store-bpel/customer_service/Dockerfile -t huuthotn01/customer-service:$imageTag . &&
          docker build -f .store-bpel/event_service/Dockerfile -t huuthotn01/event-service:$imageTag . &&
          docker build -f .store-bpel/goods_service/Dockerfile -t huuthotn01/goods-service:$imageTag . &&
          docker build -f .store-bpel/order_service/Dockerfile -t huuthotn01/order-service:$imageTag . &&
          docker build -f .store-bpel/staff_service/Dockerfile -t huuthotn01/staff-service:$imageTag . &&
          docker build -f .store-bpel/statistic_service/Dockerfile -t huuthotn01/statistic-service:$imageTag . &&
          docker build -f .store-bpel/warehouse_service/Dockerfile -t huuthotn01/warehouse-service:$imageTag . 

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: huuthotn01/admin-bff:$imageTag , huuthotn01/customer-bff:$imageTag , huuthotn01/shared-bff:$imageTag , huuthotn01/account-service:$imageTag , huuthotn01/branch-service:$imageTag , huuthotn01/cart-service:$imageTag , huuthotn01/customer-service:$imageTag , huuthotn01/event-service:$imageTag , huuthotn01/goods-service:$imageTag , huuthotn01/order-service:$imageTag , huuthotn01/staff-service:$imageTag , huuthotn01/statistic-service:$imageTag , huuthotn01/warehouse-service:$imageTag
