name: Go test

on:
  push:
    branches: [ "master", "tho/*", "phong/*", "hien/*"]

jobs:
  go-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: go test -cover ./...
