name: Docker Image CI

on:
  push:
    branches: [ "master", "tho/*", "phong/*", "hien/*"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - 
      name: Go test
      run: |
        ls
        pwd
        cd ../../account_service/internal/controller && go test && cd ../../../
        cd branch_service/internal/controller && go test && cd ../../../
        cd cart_service/internal/controller && go test && cd ../../../
        cd customer_service/internal/controller && go test && cd ../../../
        cd event_service/internal/controller && go test && cd ../../../
        cd goods_service/internal/controller && go test && cd ../../../
        cd order_service/internal/controller && go test && cd ../../../
        cd staff_service/internal/controller && go test && cd ../../../
        cd statistic_service/internal/controller && go test && cd ../../../
        cd warehouse_service/internal/controller && go test && cd ../../../
